sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")
Fix: Make sure your connection port is accurate

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
Fix: Make sure you're using the correct password

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'ro'@'localhost' (using password: YES)")
Fix: Make sure you're using the correct username

ql/mysqlconnection.py", line 8
    'database': , # we got db as an argument
Fix: Make sure there is a database name given
